import React from 'react'
import SimpleProjectPreview from '../../Components/SimpleProjectPreview'
import SimpleSidebar from '../../Components/SimpleSidebar'
import '../../Styles/Simple/Software.css'
import PulsePursuit from '../../Assets/Images/PulsePursuit.GIF'
import TapeDeck from '../../Assets/Images/TapeDeck.GIF'
import SimpleProjectCard from '../../Components/SimpleProjectCard'

function Simple() {
    return (
        <body id='simpleBody'>
            <div className='bufferSpace1'>01 [Ricky Huynh 2024]</div>
            <SimpleSidebar />
            <div className='bufferSpace3'>
                <SimpleProjectPreview
                    image='https://github.com/zzz-Ricky/time-tablez/assets/120093810/543dbaf1-3615-474d-9290-c43c32aa434f'
                    title='TimeTablez'
                    description='Time tablez is an ICS calendar visualization and comparison tool based on electron-react-boilerplate. The app is intended to be used with iCalendar format (.ics) schedule files commonly used by university time tables and events generated by popular apps such as Microsoft Outlook. TimeTablez is mainly written in Javascript with Electron and React.'
                    languages='React, Electron (Windows), TypeScript, JavaScript, CSS'
                    link='https://github.com/zzz-Ricky/time-tablez'
                />
                <SimpleProjectPreview
                    image={TapeDeck}
                    title='TapeDeck'
                    description='TapeDeck is a video platform which enables users to post and view video clips in private locally hosted communities. Enjoy the convenience of accessing clips from a mobile interface while enjoying the privacy and control of user maintained community hubs.'
                    languages='React-Native (Android), TypeScript, JavaScript, CSS'
                    link='[In private development]'
                />
                <SimpleProjectPreview
                    image={PulsePursuit}
                    title='Pulse Pursuit'
                    description='Pulse Pursuit combines the feedback of real life biometrics with the thrill of an interactive gamescape. Engage in tasks such as collecting items, harnessing power-ups, and navigating a maze of rooms and obstacles whilst the game responds to the player`s heart rate.'
                    languages='Python, PyGame CE'
                    link='https://github.com/tahmeedm/Pulse-Pursuit'
                />
                <SimpleProjectPreview
                    image='https://github.com/MaiTra10/Spout/blob/main/gifs%20and%20screenshots/desktop.gif?raw=true'
                    title='Spout'
                    description='Spout aims to solve the issue of homeowners and gardeners inefficiently watering their plants. It is said that up to 50% of the water used to water plants is wasted. Then how could we help inform these people with good watering habits? With remote watering activation, water tracking and weather based watering tips.'
                    languages='QT6 (Desktop Client), Python'
                    link='https://github.com/MaiTra10/Spout'
                />
            </div>
            <div className='cardStack'>
                <p id='nowPlaying'>NOW PLAYING:</p>
                <SimpleProjectCard
                    image='https://github.com/MaiTra10/Spout/blob/main/gifs%20and%20screenshots/desktop.gif?raw=true'
                    title='Spout'
                    description='Spout aims to solve the issue of homeowners and gardeners inefficiently watering their plants. It is said that up to 50% of the water used to water plants is wasted. Then how could we help inform these people with good watering habits? With remote watering activation, water tracking and weather based watering tips.'
                    languages='QT6 (Desktop Client), Python'
                    link='https://github.com/MaiTra10/Spout'
                />
            </div>
        </body>
    )
}

export default Simple